# Generated by Django 3.2.1 on 2021-05-09 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='exceedtime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 9, 4, 12, 44, 171583, tzinfo=utc), verbose_name='到期时间'),
        ),
    ]
